### ISSUE TITLE
Improve docker-compose for using latest template

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-grafana#1]
refer to:
- https://grafana.com/docs/grafana/latest/installation/docker/

Notetice:
1. support multiple versions
2. init password
3. plugin
4. volumes

**Comment by viafcccy** [comment]
complete

**Comment by viafcccy** [comment]
![Uploading image.png…]()

**Comment by viafcccy** [comment]
![image](https://user-images.githubusercontent.com/45913187/115678700-5f036280-a384-11eb-8311-08efd3e2ad98.png)
